import { Montserrat } from "next/font/google";
import "./globals.css";
import text from "@/Components/text";


const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: text.title,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
